const catalog=[
['rd-520','Refrigeradores','NAIHO Side by Side Prime 520','assets/refrigerador-doble-puerta.png','520 L','Doble puerta','No Frost','Inox premium'],['rd-480','Refrigeradores','NAIHO French Door 480','assets/refrigerador-french-door.png','480 L','French Door','Inverter','Dispensador de agua'],['rd-500','Refrigeradores','NAIHO Side by Side Black 500','assets/refrigerador-doble-puerta.png','500 L','Doble puerta','No Frost','Black Inox'],['rd-560','Refrigeradores','NAIHO Family Duo 560','assets/refrigerador-french-door.png','560 L','French Door','Inverter','Cajones independientes'],['rd-450','Refrigeradores','NAIHO Duo Fresh 450','assets/refrigerador-doble-puerta.png','450 L','Doble puerta','Clase A','Control digital'],
['rc-300','Refrigeradores','NAIHO Clásico 300','assets/refrigerador-clasico.png','300 L','Congelador superior','Eficiente','Acero inoxidable'],['rc-260','Refrigeradores','NAIHO Urban Black 260','assets/refrigerador-clasico-negro.png','260 L','Congelador superior','Silencioso','Negro mate'],['rc-360','Refrigeradores','NAIHO Clásico Plus 360','assets/refrigerador-clasico.png','360 L','Congelador superior','No Frost','Bandejas regulables'],['rc-220','Refrigeradores','NAIHO Compact 220','assets/refrigerador-clasico-negro.png','220 L','Congelador superior','Eco','Puerta reversible'],['rc-340','Refrigeradores','NAIHO Fresh Family 340','assets/refrigerador-clasico.png','340 L','Congelador superior','Clase A','Flujo de aire múltiple'],
['c4-50','Cocinas','NAIHO Compacta 4 · 50 cm','assets/cocina-4-compacta.png','4 hornallas','50 cm','Horno compacto','Blanco'],['c4-52','Cocinas','NAIHO Inox 4 · 52 cm','assets/cocina-naiho-plata.png','4 hornallas','52 cm','Horno amplio','Acero inoxidable'],['c4-54','Cocinas','NAIHO Black 4 · 54 cm','assets/cocina-naiho-negra.png','4 hornallas','54 cm','Doble vidrio','Negro e inox'],['c4-56','Cocinas','NAIHO Repostera 4 · 56 cm','assets/cocina-naiho-plata.png','4 hornallas','56 cm','Horno para repostería','Cajón inferior'],
['c5-76','Cocinas','NAIHO Turbo 5 · 76 cm','assets/cocina-5-hornallas.png','5 hornallas','76 cm','Triple llama','Horno 90 L'],['c5-black','Cocinas','NAIHO Black Chef 5','assets/cocina-5-negra.png','5 hornallas','80 cm','Convección','Negro mate'],['c5-glass','Cocinas','NAIHO Glass 5 · 76 cm','assets/cocina-5-hornallas.png','5 hornallas','76 cm','Vidrio templado','Encendido automático'],['c5-family','Cocinas','NAIHO Family 5 · 80 cm','assets/cocina-5-negra.png','5 hornallas','80 cm','Horno 100 L','Black Inox'],['c5-master','Cocinas','NAIHO Master 5 · 82 cm','assets/cocina-5-hornallas.png','5 hornallas','82 cm','Grill a gas','Temporizador'],
['c6-90','Cocinas','NAIHO Pro 6 · 90 cm','assets/cocina-6-hornallas.png','6 hornallas','90 cm','Horno extra amplio','Acero inoxidable'],['c6-96','Cocinas','NAIHO Master 6 · 96 cm','assets/cocina-6-hornallas.png','6 hornallas','96 cm','Horno 120 L','Alta potencia'],['c6-black','Cocinas','NAIHO Black Pro 6','assets/cocina-6-hornallas.png','6 hornallas','90 cm','Convección','Black Inox'],['c6-bakery','Cocinas','NAIHO Bakery 6','assets/cocina-6-hornallas.png','6 hornallas','92 cm','Horno repostero 115 L','Termostato preciso'],['c6-family','Cocinas','NAIHO Family Max 6','assets/cocina-6-hornallas.png','6 hornallas','94 cm','Doble bandeja','Encendido automático']
].map(x=>({id:x[0],category:x[1],name:x[2],image:x[3],specs:x.slice(4)}));
const descriptions={Refrigeradores:'Conservación confiable, organización inteligente y eficiencia para proteger los alimentos de toda la familia.',Cocinas:'Fabricación brasileña, quemadores de distintas potencias y hornos amplios para cocinar y hacer repostería.'};
window.naihoCatalog=catalog;window.naihoDescriptions=descriptions;
function header(){return `<div class="topbar">Tecnología brasileña para hogares latinoamericanos <span>•</span> Garantía regional</div><header class="header"><a class="logo" href="index.html">NAIHO<span></span></a><button class="menu" aria-label="Abrir menú" aria-expanded="false"><i></i><i></i><i></i></button><nav class="nav"><a href="index.html">Inicio</a><a href="refrigeradores.html">Refrigeradores</a><a href="cocinas.html">Cocinas</a><a href="index.html#historia">Historia</a><a href="index.html#servicio">Servicio técnico</a><a href="index.html#contacto" class="nav-cta">Contáctanos</a></nav></header>`}
function footer(){return `<footer class="page-footer"><a class="logo light-logo" href="index.html">NAIHO<span></span></a><p>Electrodomésticos pensados para acompañar tu vida.</p><div><a href="index.html">Inicio</a><a href="refrigeradores.html">Refrigeradores</a><a href="cocinas.html">Cocinas</a><a href="index.html#servicio">Servicio técnico</a></div><small>© 2026 NAIHO. Todos los derechos reservados.</small></footer>`}
function card(p){return `<article class="product-card"><div class="product-image real-photo"><img src="${p.image}" alt="${p.name}"></div><div class="product-info"><small>${p.category.toUpperCase()}</small><h3>${p.name}</h3><p>${descriptions[p.category]}</p><div class="chips">${p.specs.slice(0,2).map(s=>`<span>${s}</span>`).join('')}</div><a class="card-link" href="producto.html?id=${p.id}">Ver características →</a></div></article>`}
function initMenu(){const m=document.querySelector('.menu'),n=document.querySelector('.nav');m?.addEventListener('click',()=>{const o=n.classList.toggle('open');m.setAttribute('aria-expanded',o)})}
const type=document.body.dataset.page;
if(type==='category'){const category=document.body.dataset.category==='cocinas'?'Cocinas':'Refrigeradores',items=catalog.filter(p=>p.category===category);document.body.innerHTML=header()+`<main><section class="sub-hero"><div><div class="breadcrumbs"><a href="index.html">Inicio</a><span>›</span><span>${category}</span></div><h1>${category==='Cocinas'?'14 cocinas para cada forma de cocinar.':'10 refrigeradores para cada tipo de hogar.'}</h1><p>${descriptions[category]}</p></div></section><section class="category-wrap"><div class="category-intro"><h2>${items.length} modelos disponibles</h2><p>Selecciona cualquier modelo para abrir su ficha completa y comparar capacidad, acabado y funciones.</p></div><div class="product-grid catalog-grid">${items.map(card).join('')}</div></section></main>`+footer();initMenu()}
if(type==='detail'){const id=new URLSearchParams(location.search).get('id')||document.body.dataset.product,p=catalog.find(x=>x.id===id)||catalog[0],labels=p.category==='Cocinas'?['Configuración','Ancho','Horno','Acabado']:['Capacidad','Formato','Tecnología','Característica'];document.title=p.name+' | NAIHO';document.body.innerHTML=header()+`<main class="detail"><div class="back-row"><button class="back-button" onclick="history.back()">← Volver atrás</button><a href="index.html">Ir al inicio</a><span>›</span><a href="${p.category.toLowerCase()}.html">${p.category}</a></div><div class="detail-grid"><div class="detail-photo"><img src="${p.image}" alt="${p.name}"></div><div class="detail-copy"><span class="kicker">${p.category.toUpperCase()} · INDUSTRIA BRASILEÑA</span><h1>${p.name}</h1><p class="lead">${descriptions[p.category]}</p><div class="spec-grid">${p.specs.map((s,i)=>`<div class="spec"><small>${labels[i]}</small><b>${s}</b></div>`).join('')}</div><h3>Características principales</h3><ul class="feature-list"><li>Diseño resistente para uso cotidiano</li><li>Eficiencia y funcionamiento confiable</li><li>Superficies prácticas de fácil limpieza</li><li>Garantía y servicio técnico en Bolivia</li></ul><div class="detail-actions"><a class="button primary" href="https://wa.me/591" target="_blank" rel="noopener">Consultar disponibilidad →</a><a class="button secondary" href="${p.category.toLowerCase()}.html">Ver más modelos</a></div><p class="mini-note">Las especificaciones pueden variar según el país y distribuidor.</p></div></div></main>`+footer();initMenu()}
