const products={
  'cocina-4':{category:'Cocinas',categoryUrl:'cocinas.html',name:'Cocina NAIHO 4 hornallas',image:'assets/cocina-naiho-negra.png',lead:'Compacta, resistente y equipada con un horno amplio de cocción uniforme, ideal para repostería y para el uso diario.',specs:[['Hornallas','4 a gas'],['Acabado','Acero inoxidable'],['Horno','Amplio con visor'],['Origen','Industria brasileña']],features:['Cuatro quemadores de diferentes potencias','Horno amplio ideal para tortas, panes y repostería','Parrillas resistentes y superficie de fácil limpieza','Garantía y respaldo en Latinoamérica']},
  'cocina-5':{category:'Cocinas',categoryUrl:'cocinas.html',name:'Cocina NAIHO 5 hornallas',image:'assets/cocina-5-hornallas.png',lead:'Mayor versatilidad para familias que disfrutan cocinar. Su quinta hornalla central ofrece potencia adicional y un horno de gran capacidad.',specs:[['Hornallas','5 a gas'],['Quemador central','Alta potencia'],['Horno','Gran capacidad'],['Origen','Industria brasileña']],features:['Cinco hornallas reales: cuatro exteriores y una central','Quemador central de alta potencia','Horno con visor panorámico para controlar la cocción','Diseño robusto en acero inoxidable']},
  'cocina-6':{category:'Cocinas',categoryUrl:'cocinas.html',name:'Cocina NAIHO 6 hornallas',image:'assets/cocina-6-hornallas.png',lead:'Máxima capacidad y potencia para preparaciones grandes, con seis hornallas y un horno extra amplio para cocinar sin límites.',specs:[['Hornallas','6 a gas'],['Capacidad','Extra amplia'],['Horno','Panorámico'],['Origen','Industria brasileña']],features:['Seis quemadores independientes','Parrillas continuas de alta resistencia','Horno extra amplio con distribución uniforme del calor','Ideal para familias grandes y emprendimientos gastronómicos']},
  'refrigerador-doble':{category:'Refrigeradores',categoryUrl:'refrigeradores.html',name:'Refrigerador NAIHO Doble Puerta',image:'assets/refrigerador-doble-puerta.png',lead:'Gran capacidad, organización inteligente y frío uniforme para conservar mejor los alimentos de toda la familia.',specs:[['Formato','Side by Side'],['Sistema','No Frost'],['Acabado','Acero inoxidable'],['Control','Temperatura regulable']],features:['Compartimentos independientes para refrigerador y congelador','Distribución uniforme del aire frío','Bandejas resistentes y amplio espacio interior','Funcionamiento eficiente y silencioso']},
  'refrigerador-clasico':{category:'Refrigeradores',categoryUrl:'refrigeradores.html',name:'Refrigerador NAIHO Clásico',image:'assets/refrigerador-clasico.png',lead:'Una solución práctica y eficiente con congelador superior, diseñada para aprovechar mejor el espacio de cocinas familiares.',specs:[['Formato','Congelador superior'],['Acabado','Acero inoxidable'],['Consumo','Eficiente'],['Control','Temperatura regulable']],features:['Congelador superior independiente','Bandejas ajustables para una organización flexible','Diseño compacto que aprovecha el espacio','Operación silenciosa y conservación confiable']}
};
function header(){return `<div class="topbar">Tecnología brasileña para hogares latinoamericanos <span>•</span> Garantía regional</div><header class="header"><a class="logo" href="index.html">NAIHO<span></span></a><button class="menu" aria-label="Abrir menú" aria-expanded="false"><i></i><i></i><i></i></button><nav class="nav"><a href="index.html">Inicio</a><a href="refrigeradores.html">Refrigeradores</a><a href="cocinas.html">Cocinas</a><a href="index.html#calidad">Calidad brasileña</a><a href="index.html#servicio">Servicio técnico</a><a href="index.html#contacto" class="nav-cta">Contáctanos</a></nav></header>`}
function footer(){return `<footer class="page-footer"><a class="logo light-logo" href="index.html">NAIHO<span></span></a><p>Electrodomésticos pensados para acompañar tu vida.</p><div><a href="index.html">Inicio</a><a href="refrigeradores.html">Refrigeradores</a><a href="cocinas.html">Cocinas</a><a href="index.html#servicio">Servicio técnico</a></div><small>© 2026 NAIHO. Todos los derechos reservados.</small></footer>`}
function card(id){const p=products[id];return `<article class="product-card"><div class="product-image real-photo"><img src="${p.image}" alt="${p.name}"></div><div class="product-info"><small>${p.category.toUpperCase()}</small><h3>${p.name}</h3><p>${p.lead}</p><a class="card-link" href="producto-${id}.html">Ver características →</a></div></article>`}
function initMenu(){const m=document.querySelector('.menu'),n=document.querySelector('.nav');m?.addEventListener('click',()=>{const o=n.classList.toggle('open');m.setAttribute('aria-expanded',o)})}
const type=document.body.dataset.page;
if(type==='category'){const category=document.body.dataset.category;const ids=category==='cocinas'?['cocina-4','cocina-5','cocina-6']:['refrigerador-doble','refrigerador-clasico'];const title=category==='cocinas'?'Cocinas que inspiran grandes recetas.':'Refrigeración que protege lo que importa.';document.body.innerHTML=header()+`<main><section class="sub-hero"><div><div class="breadcrumbs"><a href="index.html">Inicio</a><span>›</span><span>${category==='cocinas'?'Cocinas':'Refrigeradores'}</span></div><h1>${title}</h1><p>${category==='cocinas'?'Modelos de 4, 5 y 6 hornallas con hornos amplios, fabricación brasileña y respaldo regional.':'Modelos eficientes para conservar tus alimentos con orden, frescura y confianza.'}</p></div></section><section class="category-wrap"><div class="category-intro"><h2>Elige tu modelo</h2><p>Entra en cada producto para conocer sus características, beneficios y detalles.</p></div><div class="product-grid">${ids.map(card).join('')}</div></section></main>`+footer();initMenu()}
if(type==='detail'){const id=document.body.dataset.product,p=products[id];document.title=p.name+' | NAIHO';document.body.innerHTML=header()+`<main class="detail"><div class="back-row"><button class="back-button" onclick="history.back()">← Volver atrás</button><a href="index.html">Ir al inicio</a><span>›</span><a href="${p.categoryUrl}">${p.category}</a></div><div class="detail-grid"><div class="detail-photo"><img src="${p.image}" alt="${p.name}"></div><div class="detail-copy"><span class="kicker">${p.category.toUpperCase()} · INDUSTRIA BRASILEÑA</span><h1>${p.name}</h1><p class="lead">${p.lead}</p><div class="spec-grid">${p.specs.map(s=>`<div class="spec"><small>${s[0]}</small><b>${s[1]}</b></div>`).join('')}</div><h3>Características principales</h3><ul class="feature-list">${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><div class="detail-actions"><a class="button primary" href="https://wa.me/591" target="_blank" rel="noopener">Consultar disponibilidad →</a><a class="button secondary" href="${p.categoryUrl}">Ver más ${p.category.toLowerCase()}</a></div><p class="mini-note">Las especificaciones y disponibilidad pueden variar según el país y distribuidor.</p></div></div></main>`+footer();initMenu()}
